[openai]
api_key = "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"
prompt = "The following is a conversation with an AI assistant. The assistant is helpful, creative, clever, and very friendly.\n\n"
